development:
  secret_key_base: XXXXXXXXXXXXXXXXX
  aws_access_key_id: <%= ENV["AWS_ACCESS_KEY_ID"] %>
  aws_secret_access_key: <%= ENV["AWS_SECRET_ACCESS_KEY"] %>
  google_client_id: 426424720499-ekv9hrjuc9o7hms3unqci4cfepnmogdf.apps.googleusercontent.com
  google_client_secret: BB-b0txPjzPm5RrxmOYLpGT5

test:
  secret_key_base: ~~~~~~~~

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  aws_access_key_id: <%= ENV["AWS_ACCESS_KEY_ID"] %>
  aws_secret_access_key: <%= ENV["AWS_SECRET_ACCESS_KEY"] %>

